runtime:
  cache_dir: ./.cache/antora

site:
  title: Advanced DevSecOps Workshop
  url: https://github.com/OpenShiftDemos/advanced-devsecops-workshop
  start_page: advanced-devsecops-workshop::index.adoc

content:
  sources:
    - url: ./
      start_path: documentation

asciidoc:
  attributes:
    release-version: main
    page-pagination: true
  extensions:
    - ./lib/tab-block.js
    - ./lib/remote-include-processor.js

ui:
  bundle:
    url: https://github.com/evanshortiss/course-ui/releases/download/v0.1.13-prerelease/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

output:
  dir: ./gh-pages
