apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: rekor-verify
spec:
  params:
    - default: quay
      name: registrySecret
      type: string
    - default: cosign-secret
      name: cosignSecret
      type: string
    - default: >-
        quay-8hvtv.apps.cluster-8hvtv.8hvtv.sandbox2411.opentlc.com/quayadmin/globex-ui:main-e39ea4710cfe0639f5343ef62695dae5f310d566
      name: image
      type: string
  stepTemplate:
    env:
      - name: "TUF_URL"
        value: "http://tuf.trusted-artifact-signer.svc"
      - name: "COSIGN_MIRROR"
        value: "http://tuf.trusted-artifact-signer.svc"
      - name: "COSIGN_ROOT"
        value: "http://tuf.trusted-artifact-signer.svc/root.json"
      - name: "COSIGN_REKOR_URL"
        value: "http://rekor-server.trusted-artifact-signer.svc"
      - name: "SIGSTORE_REKOR_URL"
        value: "http://rekor-server.trusted-artifact-signer.svc"
      - name: "REKOR_REKOR_SERVER"
        value: "http://rekor-server.trusted-artifact-signer.svc"
      - name: "COSIGN_FULCIO_URL"
        value: "http://fulcio-server.trusted-artifact-signer.svc"
      - name: COSIGN_YES
        value: "true"
      - name: SIGSTORE_FULCIO_URL
        value: "http://fulcio-server.trusted-artifact-signer.svc"
  steps:
    - env:
        - name: REGISTRY_SECRET
          valueFrom:
            secretKeyRef:
              key: .dockerconfigjson
              name: $(params.registrySecret)
        - name: COSIGN_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              key: cosign.pub
              name: $(params.cosignSecret)
      image: registry.redhat.io/rhtas/cosign-rhel9:1.1.0 #quay.io/redhat-gpte/cosign
      name: cosign-verify-image
      resources: {}
      script: |
        #!/usr/bin/env bash

        # Initialize cosign with certs based on environment variables
        cosign initialize

        echo "cosign has been initialized"

        echo "${COSIGN_PUBLIC_KEY}" > /workspace/cosign.pub

        cosign verify --key /workspace/cosign.pub $(params.image) --output-file /workspace/cosign.verify
    - image: quay.io/redhat-gpte/jq
      name: extract-signature-details
      resources: {}
      script: >
        cat /workspace/cosign.verify | jq --raw-output '.[0] | .critical | .image | .["docker-manifest-digest"]' >
        /workspace/cosign.sha
    - image: quay.io/redhat-gpte/rekor-cli
      name: rekor-search-sha
      resources: {}
      script: >
        rekor-cli search --sha $(cat /workspace/cosign.sha) --format json >
        /workspace/rekor.search
    - image: quay.io/redhat-gpte/jq
      name: rekor-extract-uuid
      resources: {}
      script: >
        cat /workspace/rekor.search | jq '.UUIDs[0]' | sed 's/\"//g' >
        /workspace/rekor.uuid
    - image: quay.io/redhat-gpte/rekor-cli
      name: rekor-get-with-uuid
      resources: {}
      script: >
        rekor-cli get --uuid $(cat /workspace/rekor.uuid) --format json >
        /workspace/rekor.get
    - image: quay.io/redhat-gpte/jq
      name: verify-attestation
      resources: {}
      script: |
        cat /workspace/rekor.get | jq -r .Attestation
