apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline-helm
spec:
  destination:
    namespace: ${USER}-cicd
    name: in-cluster
  source:
    path: globex-ui
    repoURL: 'https://github.com/jchraibi/helm-chart.git'
    targetRevision: main
  sources: []
  project: ${USER}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
