apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coolstore-app
spec:
  destination:
    namespace: $USER-cicd
    name: in-cluster
  project: $USER
  source:
    path: content/modules/ROOT/files/gitops/module-02
    repoURL: https://github.com/AdvancedDevSecOpsWorkshop/workshop.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
