apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: app-globex-ui-pipeline-
spec:
  params:
    - name: REPO_HOST
      value: gitea-gitea.$SUBDOMAIN
    - name: GIT_REPO
      value: 'https://gitea-gitea.$SUBDOMAIN/$USER/web-nodejs.git'
    - name: TLSVERIFY
      value: 'false'
    - name: BUILD_EXTRA_ARGS
      value: $(tt.params.build_extra_args)
    - name: IMAGE_REPO
      value: registry-quay-quay-operator.$SUBDOMAIN/workshop$USERNUM/globex-ui
    - name: IMAGE_TAG
      value: main-b183894cabd3eebaa5844143d5ac60dc9863fb57
    - name: MANIFEST_FILE
      value: globex/overlays/dev/kustomization.yaml
    - name: MANIFEST_FILE_PROD
      value: globex/overlays/prod/kustomization.yaml
    - name: MANIFEST_REPO
      value: 'https://gitea-gitea.$SUBDOMAIN/$USER/gitops'
    - name: MANIFEST_REPO_NAME
      value: $USER/gitops
    - name: COMMIT_SHA
      value: b183894cabd3eebaa5844143d5ac60dc9863fb57
    - name: GIT_REF
      value: main
    - name: COMMIT_DATE
      value: '2024-11-03T22:04:11Z'
    - name: COMMIT_AUTHOR
      value: $USER
    - name: COMMIT_MESSAGE
      value: |
        Updates for starting scenario.
    - name: SONARQUBE_HOST_URL
      value: 'https://sonarqube-$USER-cicd.$SUBDOMAIN'
    - name: SONARQUBE_PROJECT_KEY
      value: globex-ui
    - name: SONARQUBE_PROJECT_SECRET
      value: sonarqube-admin
    - name: CYCLONEDX_HOST_URL
      value: 'https://cyclonedx-bom-repo-server-cyclonedx.$SUBDOMAIN'
  pipelineRef:
    name: app-globex-ui-pipeline
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
        status: {}
    - emptyDir: {}
      name: maven-settings
