apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline-helm-params
spec:
  destination:
    namespace: user1-cicd
    name: in-cluster
  source:
    path: content/modules/ROOT/examples/globex-ui
    repoURL: 'https://github.com/AdvancedDevSecOpsWorkshop/workshop.git'
    targetRevision: main
    helm:
      parameters:
        - name: globex.registry.imageRepo
          value: 'custom-image-repo'
        - name: sonarqube.hostUrl
          value: 'custom-sonar-host'
  sources: []
  project: user1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true