apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline-helm-custom-values
spec:
  destination:
    namespace: $USER-cicd
    name: in-cluster
  source:
    path: content/modules/ROOT/examples/globex-ui
    repoURL: 'https://gitea-gitea.$SUBDOMAIN/$USER/workshop.git'
    targetRevision: main
    helm:
      valueFiles:
        - custom_values_1/values.yaml
  sources: []
  project: $USER
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: ""
    kind: ServiceAccount
    name: pipeline
    jsonPointers:
    - /imagePullSecrets
