apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline-helm
spec:
  destination:
    namespace: $USER-cicd
    name: in-cluster
  source:
    path: content/modules/ROOT/examples/globex-ui
    repoURL: 'https://gitea-gitea.$SUBDOMAIN/$USER/workshop.git'
    targetRevision: main
  sources: []
  project: $USER
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: false
  ignoreDifferences:
  - group: ""
    kind: ServiceAccount
    name: pipeline
    jsonPointers:
    - /imagePullSecrets
