apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline-helm-params
spec:
  destination:
    namespace: $USER-cicd
    name: in-cluster
  source:
    path: content/modules/ROOT/examples/globex-ui
    repoURL: 'https://github.com/AdvancedDevSecOpsWorkshop/workshop.git'
    targetRevision: main
    helm:
      parameters:
        - name: globex.registry.url
          value: 'registry-quay-quay-operator.apps.cluster-424xp.424xp.sandbox1774.opentlc.com'
        - name: sonarqube.hostUrl
          value: 'https://sonarqube-user49-cicd.apps.cluster-424xp.424xp.sandbox1774.opentlc.com'
  sources: []
  project: $USER
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: ""
    kind: ServiceAccount
    name: pipeline
    jsonPointers:
    - /imagePullSecrets
