apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-prod
  namespace: $USER-argocd
spec:
  destination:
    name: in-cluster
    namespace: $USER-prod
  project: $USER
  source:
    path: globex/overlays/prod
    repoURL: 'https://gitea-gitea.$SUBDOMAIN/$USER/gitops.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
