apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-dev
  namespace: $USER-argocd
spec:
  destination:
    name: in-cluster
    namespace: $USER-dev
  project: $USER
  source:
    path: globex/overlays/dev
    repoURL: 'https://gitea-gitea.$SUBDOMAIN/$USER/gitops.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true